# Configuration for LQG Positive Matter Assembler

# System Configuration
system:
  # Safety parameters (10¹² biological protection margin)
  safety_factor: 1.0e12
  emergency_response_time: 1.0e-6  # 1 microsecond
  
  # LQG parameters
  polymer_scale_mu: 0.7  # Optimal LQG polymer scale
  volume_quantization: true
  planck_length: 1.616e-35  # meters
  planck_mass: 2.176e-8     # kg
  
  # Computational parameters
  numerical_precision: 1.0e-12
  integration_tolerance: 1.0e-10
  max_iterations: 10000
  convergence_threshold: 1.0e-8

# Positive Matter Assembly Configuration
matter_assembly:
  # Target parameters
  default_target_density: 1000.0  # kg/m³ (water density)
  default_assembly_radius: 5.0    # meters
  default_assembly_time: 10.0     # seconds
  
  # Spatial discretization
  spatial_resolution: 20     # Points per dimension
  temporal_resolution: 50    # Time steps
  
  # Energy conditions enforcement
  energy_conditions:
    enforce_weak: true      # T_μν u^μ u^ν ≥ 0
    enforce_null: true      # T_μν k^μ k^ν ≥ 0
    enforce_dominant: true  # T_μν ≥ 0 eigenvalues
    enforce_strong: true    # (T_μν - ½gμν T) u^μ u^ν ≥ 0
    
  # Conservation validation
  conservation_tolerance: 0.001  # 0.1% maximum error
  mass_conservation: true
  energy_conservation: true
  momentum_conservation: true

# Bobrick-Martire Geometry Configuration
geometry:
  # Optimization targets
  energy_efficiency_target: 1.0e5   # 100,000× improvement target
  causality_preservation: true
  temporal_coherence_target: 0.999  # 99.9% coherence
  
  # Geometry parameters
  smoothness_order: 4       # C⁴ smoothness
  boundary_conditions: "smooth"
  metric_signature: "-+++"  # Minkowski signature
  
  # Warp parameters
  max_warp_velocity: 0.5    # 0.5c maximum (subluminal)
  warp_bubble_thickness: 2.0  # Bubble wall thickness
  transition_smoothness: 1.0  # Smooth transitions
  
  # Optimization settings
  optimization_method: "gradient_descent"
  learning_rate: 0.001
  momentum: 0.9
  max_optimization_steps: 1000

# Stress-Energy Tensor Control
stress_energy:
  # Monitoring parameters
  monitoring_interval_ms: 1.0     # Real-time monitoring every 1ms
  constraint_check_frequency: 100  # Hz
  
  # Validation thresholds
  positive_energy_threshold: 1.0e-15    # Minimum positive energy
  pressure_bounds: [-1.0e10, 1.0e15]   # Pascal
  density_bounds: [0.0, 1.0e20]        # kg/m³
  
  # Emergency protocols
  emergency_termination_threshold: 1.0e-8
  violation_tolerance: 3  # Number of consecutive violations before emergency stop
  
  # Einstein field equations
  cosmological_constant: 0.0      # Λ = 0 (no dark energy)
  gravitational_constant: 6.674e-11  # m³ kg⁻¹ s⁻²
  speed_of_light: 299792458.0     # m/s

# Integration Configuration
integration:
  # Repository paths (relative to project root)
  repository_paths:
    unified_lqg: "../unified-lqg"
    artificial_gravity: "../artificial-gravity-field-generator"
    warp_optimizer: "../warp-bubble-optimizer"
    negative_energy: "../negative-energy-generator"
    simulation_framework: "../enhanced-simulation-hardware-abstraction-framework"
    volume_controller: "../lqg-volume-quantization-controller"
    stability_controller: "../warp-spacetime-stability-controller"
    matter_transporter: "../polymerized-lqg-matter-transporter"
    unified_qft: "../unified-lqg-qft"
    warp_qft: "../warp-bubble-qft"
    su2_closedform: "../su2-3nj-closedform"
    
  # Integration priorities (1 = highest, 3 = lowest)
  tier_1_repositories: ["unified-lqg", "artificial-gravity"]
  tier_2_repositories: ["warp-optimizer", "negative-energy", "simulation-framework"]
  tier_3_repositories: ["volume-controller", "stability-controller", "matter-transporter"]
  
  # Data exchange formats
  data_format: "hdf5"
  coordinate_system: "cartesian"
  units_system: "SI"

# Visualization Configuration
visualization:
  # Plot settings
  figure_size: [12, 10]
  dpi: 300
  colormap: "viridis"
  
  # Animation settings
  animation_fps: 30
  animation_duration: 10.0  # seconds
  
  # 3D visualization
  render_quality: "high"
  lighting: "physical"
  camera_position: [10, 10, 10]

# Logging Configuration
logging:
  # Log levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # Output destinations
  console: true
  file: true
  log_file: "lqg_positive_matter_assembler.log"
  
  # Rotation settings
  max_file_size: "10MB"
  backup_count: 5
  
  # Format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

# Performance Configuration
performance:
  # Parallel processing
  use_multiprocessing: true
  max_workers: 8  # Adjust based on CPU cores
  
  # Memory management
  memory_limit_gb: 16.0
  garbage_collection: true
  
  # Caching
  enable_caching: true
  cache_size_mb: 1024
  
  # Optimization
  use_numba_jit: true
  vectorization: true

# Testing Configuration
testing:
  # Test parameters
  test_spatial_resolution: 10
  test_time_resolution: 20
  test_assembly_radius: 2.0
  test_target_density: 1000.0
  test_safety_factor: 1.0e6
  
  # Tolerances
  numerical_tolerance: 1.0e-6
  conservation_tolerance: 1.0e-4
  
  # Timeout
  test_timeout_seconds: 30.0
  
  # Coverage
  minimum_coverage: 90.0  # Percent

# Development Configuration
development:
  # Debug settings
  debug_mode: false
  verbose_output: false
  
  # Validation
  strict_validation: true
  type_checking: true
  
  # Documentation
  auto_generate_docs: true
  include_examples: true
